config/routes.rb
Pictures::Application.routes.draw do
  devise_for :users

  resources :pictures do
    resources :comments
  end

  root :to => redirect('/pictures')

  match '*path' => redirect('/')

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		user ||= User.new # guest user

		if user.role? :Admin
			can :manage, :all
			can :publish, Picture
		elsif user.role? :Member
			can :read, :all
			can :create, Comment
			#can [:edit, :update], Comment
		end
	end
		
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
  belongs_to :user
  attr_accessible :body, :commenter

  validates :body, :presence => true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	
	mount_uploader :picture, PictureUploader

	attr_accessible :description, :name, :picture, :tags_attributes

	has_many :comments, :dependent => :destroy
	has_many :tags, :dependent => :destroy

	validates :picture, :presence => true
	validates :name, :presence => true
					
	
  	accepts_nested_attributes_for :tags, :allow_destroy => :true,
    	:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }	
	
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :picture
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

	has_and_belongs_to_many :roles

	has_many :comments

	before_create :setup_role

	def role?(role)
		return !!self.roles.find_by_name(role.to_s)
 	end

	
	private
	def setup_role
  		if self.role_ids.empty?
    	self.role_ids = [2]
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	#@username = User.find(session[:user_id]).email

	def create
	    @picture = Picture.find(params[:picture_id])
	    @comment = @picture.comments.create(params[:comment])
	    redirect_to picture_path(@picture)
	end

	def destroy
    	@picture = Picture.find(params[:picture_id])
    	@comment = @picture.comments.find(params[:id])
    	@comment.destroy
    	redirect_to picture_path(@picture)
  	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  
  
  
  
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    @temppicture = Picture.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])
    #@username = User.find(session[:user_id]).email
    @tempcomment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    authorize! :create, @picture
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    authorize! :edit, @picture
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    authorize! :update, @picture
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    authorize! :destroy, @picture
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
	def join_tags(picture)
    picture.tags.map { |t| t.name }.join(", ")
  end
end

app/views/comments/_comment.html.erb
<p>
    <b><%= comment.commenter %></b> <b> wrote:</b>
</p>
 
<p>
  <b></b>
  <%= comment.body %>
</p>
 
<p>
	<% if can? :destroy, comment  %>
  		<%= link_to 'Destroy Comment', [comment.picture, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
    <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@picture, @picture.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter, :value => current_user.email, :readonly => true  %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pictures</title>
 
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Album Site</a>
      <ul class="nav">
        <li class="active"><a href="/pictures">Pictures</a></li>
      </ul>
      <p class="navbar-text pull-right">
		<% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
  			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
  			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>
    </div>
  </div>
</div>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Album Site
  </div>
</footer>



</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |picture_form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= picture_form.label :name %><br />
    <%= picture_form.text_field :name %>
  </div>
  <div class="field">
    <%= picture_form.label :picture %><br />
    <%= picture_form.file_field :picture %>
  </div>
  <div class="field">
    <%= picture_form.label :description %><br />
    <%= picture_form.text_field :description %>
  </div>
  <h3>Tags</h3>
  <%= render :partial => 'tags/form',
             :locals => {:form => picture_form} %>
  <div class="actions">
    <%= picture_form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Picture</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.name %></td>
    <td><%= image_tag(picture.picture_url, :size => '90x90') %></td>
    <td><%= picture.description %></td>

    <td><%= link_to 'Show', picture %></td>
    <% if can? :update, picture  %>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <% end %>
    <% if can? :delete, picture  %>
    <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, @temppicture  %>
<%= link_to 'New Picture', new_picture_path %>
<% end %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @picture.name %>
</p>

<p>
  <%= image_tag(@picture.picture_url, :width => 600) if @picture.picture.present? %>
</p>

<p>
  <b>Description:</b>
  <%= @picture.description %>
</p>

<p>
  <b>Tags:</b>
  <%= join_tags(@picture) %>
</p>

<h3>Comments</h3>
<%= render @picture.comments %>

<% if can? :create, @tempcomment  %>
<p>Add a comment:</p>
<%= render "comments/form" %>
<% end %>

<p><%#= current_user.email %></p>

<br />

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back to Pictures', pictures_path %>

app/views/tags/_form.html.erb
<% @picture.tags.build %>
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>